<?PHP

$garmin_symbols = array(
    'Airport',
    'Amusement Park',
    'Anchor Prohibited',
    'Anchor',
    'Animal Tracks',
    'Asian Food',
    'ATV',
    'Bait and Tackle',
    'Ball Park',
    'Bank',
    'Bar',
    'Beach',
    'Beacon',
    'Bell',
    'Big Game',
    'Bike Trail',
    'Blind',
    'Block, Blue',
    'Block, Green',
    'Block, Red',
    'Blood Trail',
    'Boat Ramp',
    'Border Crossing (Port Of Entry)',
    'Bottom Conditions',
    'Bowling',
    'Bridge',
    'Building',
    'Buoy, White',
    'Campground',
    'Car Rental',
    'Car Repair',
    'Car',
    'Cemetery',
    'Church',
    'Circle with X',
    'Circle, Blue',
    'Circle, Green',
    'Circle, Red',
    'City (Capitol)',
    'City (Large)',
    'City (Medium)',
    'City (Small)',
    'City Hall',
    'Civil',
    'Coast Guard',
    'Contact, Afro',
    'Contact, Alien',
    'Contact, Ball Cap',
    'Contact, Biker',
    'Contact, Blonde',
    'Contact, Bug',
    'Contact, Cat',
    'Contact, Clown',
    'Contact, Dog',
    'Contact, Dreadlocks',
    'Contact, Female1',
    'Contact, Female2',
    'Contact, Female3',
    'Contact, Glasses',
    'Contact, Goatee',
    'Contact, Kung-Fu',
    'Contact, Panda',
    'Contact, Pig',
    'Contact, Pirate',
    'Contact, Ranger',
    'Contact, Smiley',
    'Contact, Spike',
    'Contact, Sumo',
    'Controlled Area',
    'Convenience Store',
    'Cover',
    'Covey',
    'Crossing',
    'Dam',
    'Danger Area',
    'Deli',
    'Department Store',
    'Diamond, Blue',
    'Diamond, Green',
    'Diamond, Red',
    'Diver Down Flag 1',
    'Diver Down Flag 2',
    'Dock',
    'Dot, White',
    'Drinking Water',
    'Dropoff',
    'Elevation point',
    'Event Cache',
    'Exit without services',
    'Exit',
    'Fast Food',
    'First approach fix',
    'Fishing Area',
    'Fishing Hot Spot Facility',
    'Fitness Center',
    'Flag, Blue',
    'Flag, Green',
    'Flag, Red',
    'Flag',
    'Food Source',
    'Forest',
    'Furbearer',
    'Gambling/casino',
    'Gas Station',
    'Geocache Found',
    'Geocache',
    'Geographic place name, land',
    'Geographic place name, Man-made',
    'Geographic place name, water',
    'Ghost Town',
    'Glider Area',
    'Golf Course',
    'Ground Transportation',
    'Heliport',
    'Horn',
    'Hotel',
    'House',
    'Hunting Area',
    'Ice Skating',
    'Information',
    'Intersection',
    'Intl freeway hwy',
    'Intl national hwy',
    'Italian food',
    'Large exit without services',
    'Large Ramp intersection',
    'Letter A, Blue',
    'Letter A, Green',
    'Letter A, Red',
    'Letter B, Blue',
    'Letter B, Green',
    'Letter B, Red',
    'Letter C, Blue',
    'Letter C, Green',
    'Letter C, Red',
    'Letter D, Blue',
    'Letter D, Green',
    'Letter D, Red',
    'Letterbox Cache',
    'Levee',
    'Library',
    'Light',
    'Live Theater',
    'Localizer Outer Marker',
    'Locationless (Reverse) Cache',
    'Lodge',
    'Lodging',
    'Man Overboard',
    'Marina',
    'Medical Facility',
    'Micro-Cache',
    'Mile Marker',
    'Military',
    'Mine',
    'Missed approach point',
    'Movie Theater',
    'Multi-Cache',
    'Museum',
    'Navaid, Amber',
    'Navaid, Black',
    'Navaid, Blue',
    'Navaid, Green/Red',
    'Navaid, Green/White',
    'Navaid, Green',
    'Navaid, Orange',
    'Navaid, Red/Green',
    'Navaid, Red/White',
    'Navaid, Red',
    'Navaid, Violet',
    'Navaid, White/Green',
    'Navaid, White/Red',
    'Navaid, White',
    'Non-directional beacon',
    'Null',
    'Number 0, Blue',
    'Number 0, Green',
    'Number 0, Red',
    'Number 1, Blue',
    'Number 1, Green',
    'Number 1, Red',
    'Number 2, Blue',
    'Number 2, Green',
    'Number 2, Red',
    'Number 3, Blue',
    'Number 3, Green',
    'Number 3, Red',
    'Number 4, Blue',
    'Number 4, Green',
    'Number 4, Red',
    'Number 5, Blue',
    'Number 5, Green',
    'Number 5, Red',
    'Number 6, Blue',
    'Number 6, Green',
    'Number 6, Red',
    'Number 7, Blue',
    'Number 7, Green',
    'Number 7, Red',
    'Number 8, Blue',
    'Number 8, Green',
    'Number 8, Red',
    'Number 9, Blue',
    'Number 9, Green',
    'Number 9, Red',
    'Oil Field',
    'Open 24 Hours',
    'Oval, Blue',
    'Oval, Green',
    'Oval, Red',
    'Parachute Area',
    'Park',
    'Parking Area',
    'Pharmacy',
    'Picnic Area',
    'Pin, Blue',
    'Pin, Green',
    'Pin, Red',
    'Pizza',
    'Police Station',
    'Post Office',
    'Post Office',
    'Private Field',
    'Radio Beacon',
    'Ramp intersection',
    'Rectangle, Blue',
    'Rectangle, Green',
    'Rectangle, Red',
    'Reef', 'Webcam Cache',
    'Residence',
    'Restaurant',
    'Restricted Area',
    'Restroom',
    'RV Park',
    'Scales',
    'Scenic Area',
    'School',
    'Seafood',
    'Seaplane Base',
    'Shipwreck',
    'Shopping Center',
    'Short Tower',
    'Shower',
    'Ski Resort',
    'Skiing Area',
    'Skull and Crossbones',
    'Small City',
    'Small Game',
    'Soft Field',
    'Square, Blue',
    'Square, Green',
    'Square, Red',
    'Stadium',
    'State Hwy',
    'Steak',
    'Street Intersection',
    'Stump',
    'Summit',
    'Swimming Area',
    'TACAN',
    'Tall Tower',
    'Telephone',
    'Tide/Current Prediction Station',
    'Toll Booth',
    'TracBack Point',
    'Trail Head',
    'Tree Stand',
    'Treed Quarry',
    'Triangle, Blue',
    'Triangle, Green',
    'Triangle, Red',
    'Truck Stop',
    'Truck',
    'Tunnel',
    'U Marina',
    'U stump',
    'Ultralight Area',
    'Unknown Cache',
    'Upland Game',
    'US hwy',
    'VHF Omni-range',
    'Virtual cache',
    'VOR/TACAN',
    'Water Hydrant',
    'Water Source',
    'Waterfowl',
    'Waypoint',
    'Weed Bed',
    'Winery',
    'Wrecker',
    'Zoo'
);